training_params:
  max_epochs: 80
  auto_lr_find: false
  gpus: 0
model_params:
  model_type: conv-vae # vae or conv-vae
  lr: 0.005
  batch_size: 144
  hidden_size: 32
  alpha: 1024 # balance of reconstruction loss and prior distribution loss
  dataset: "bar"
  save_images: true
  save_path: "../out/vae_digit"
  channels: 3
  height: 28
  width: 28
  data_path: "../dat"
logger_params:
  name: "conv-vae"
  save_dir: "../out/vae_digit"